name: Deploy Dist
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: install node js
              uses:  actions/setup-node@v6
              with:
                node-version: 22
            - name: Install dependancies 
              run: npm install
            - name: Run Tests
              run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: install node js
              uses:  actions/setup-node@v6
              with:
                node-version: 22
            - name: Install dependancies 
              run: npm install
            - name: Run Build
              run: npm run build

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Dist
              run: echo "Deployment Completed"