name: Deploy Dist
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              run: |
                echo "cloning the repository"
                echo "${{toJson(github)}}"
                git clone https://github.com/${{github.repository}}.git myfiles
                cd myfiles && ls
        