name: greer user
on: push
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: greet user
              run: echo "hello world"
            - name: bye user
              run: echo "bye bye"